### ISSUE TITLE
Future features / TODO dump

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-cards#13]
- [ ] unify and streamline generation of HTML counter / tracker. Single Handlebars function that takes multiple arguments. How do I write this to be testable? It outputs HTML, so I could write HTML-based test cases.
- [ ] replace Swag since that library is no longer supported. http://assemble.io/helpers/ - requires using browserify or webpack
- [ ] update version of Handlebars in use (from 3 to 4)
- [ ] Move style / formatting classes that're being applied to body to #renderArea (special case: print instructions? show that div in the JS?) these're currently scattered throughout all scss
- [ ] uglify / compress app.bundle.js
- [ ] add support to official + print and play templates for user-specified watermark on the back, kind of like the `naming` column (maybe just make `naming` generic / `watermark`?)

---

Use React and Redux, would make all of these notably easier / saner

`Data.validate function (sheets) => ([errs], sheets)`
- data.js should contain (private) data schema for all templates
- errors should include template, row number and column name, plus validation error

Test cases for individual functions, plus integration tests:
- one card from one template, valid and returns card
- one card from each template, valid and returns cards
- one card from one template, missing a field, returns validation error
- one card from one template, field improperly typed (ie string when expecting number), returns validation error

---
- in the UI, show all output errors in a modal
- make sure it accepts data sources that contain as little as one card of one template
- make sure it doesn't break if the data source contains extra info
- code it to contain the full schema for each table
- validate each table and card on load
- delivery all validation errors in a close-able modal (but still render the cards)
